// Generated by CoffeeScript 1.7.1
(function() {
  var base_url;

  base_url = "http://localhost:5000/";

  window.onload = function() {
    var canvas, curr_zoom, hitOptions, isDragging, paper, prevDragPosition;
    hitOptions = {
      segments: true,
      stroke: true,
      curves: true,
      handles: true,
      fill: true,
      tolerance: 10
    };
    paper = window.paper;
    canvas = document.getElementById('canvas');
    paper.setup(canvas);
    window.mainCanvas = paper.projects[0];
    api.populatePaper();
    mainCanvas.activate();
    paper.view.draw();
    segmentation_tool.activate();
    curr_zoom = 1;
    isDragging = false;
    prevDragPosition = [0, 0];
    $('#canvas').on('mousewheel', function(event) {
      var a, beta, d, p, pc, zoom_factor;
      mainCanvas.activate();
      if (event.altKey) {
        return paper.view.center = paper.view.center.add(new paper.Point(event.deltaX * 10, event.deltaY * 10));
      } else {
        d = event.deltaY;
        zoom_factor = 1;
        if (d > 0) {
          zoom_factor = Math.pow(0.8, d);
        } else {
          zoom_factor = Math.pow(1.2, Math.abs(d));
        }
        beta = 1 / zoom_factor;
        curr_zoom = curr_zoom * zoom_factor;
        p = new paper.Point(event.pageX, event.pageY);
        pc = p.subtract(paper.view.center);
        a = p.subtract(pc.multiply(beta)).subtract(paper.view.center);
        paper.view.zoom = curr_zoom;
        return paper.view.center = paper.view.center.add(a);
      }
    });
    $('#testbtn').click(function() {
      var dx, dy, segment, vector;
      dx = 1;
      dy = 0;
      mainCanvas.activate();
      segment = mainCanvas.selectedItems[0];
      if (!segment.is_segment) {
        return;
      }
      if (vector) {
        vector = vector.normalize();
        dx = vector.x;
        dy = vector.y;
      }
      return changeFill(segment, vector);
    });
    $('#resegment').click(function() {
      return segmentation_tool.activate();
    });
    $('#fill').click(function() {
      return fill_select_tool.activate();
    });
    $('#connections').click(function() {
      return modify_connections_tool.activate();
    });
    return $('#shape_transitions').click(function() {
      console.log("activating the shape transition tool");
      return shape_transition_curve_tool.activate();
    });
  };

}).call(this);
