// Generated by CoffeeScript 1.7.1
(function() {
  var handle, handle2, node, tool;

  window.shape_transition_curve_tool = new paper.Tool();

  tool = shape_transition_curve_tool;

  tool.minDistance = 0;

  handle = handle2 = node = null;

  tool.init = function() {
    var bezier_Path, hitOptions;
    hitOptions = {
      segments: true,
      stroke: true,
      handles: true,
      tolerance: 10
    };
    bezier_Path = new paper.Path();
    bezier_Path.add([10, 10]);
    bezier_Path.add(new paper.Segment(new paper.Point(100, 200), new paper.Point(-30, -40), new paper.Point(40, 50)));
    bezier_Path.add([300, 400]);
    bezier_Path.strokeColor = 'green';
    bezier_Path.strokeWidth = 3;
    bezier_Path.fullySelected = true;
    tool.onMouseDown = function(event) {
      var hitResult, location, segment;
      node = handle = handle2 = null;
      hitResult = bezier_Path.hitTest(event.point, hitOptions);
      if (hitResult) {
        console.log(hitResult);
        if (hitResult.type === 'handle-in') {
          handle2 = hitResult.segment.handleOut;
          return handle = hitResult.segment.handleIn;
        } else if (hitResult.type === 'handle-out') {
          handle2 = hitResult.segment.handleIn;
          return handle = hitResult.segment.handleOut;
        } else if (hitResult.type === 'segment') {
          return node = hitResult.segment.point;
        } else if (hitResult.type === 'stroke') {
          location = hitResult.location;
          return segment = path.insert(location.index + 1, event.point);
        }
      }
    };
    return tool.onMouseDrag = function(event) {
      if (handle) {
        handle.x += event.delta.x;
        handle.y += event.delta.y;
        handle2.x -= event.delta.x;
        return handle2.y -= event.delta.y;
      } else if (node) {
        node.x += event.delta.x;
        return node.y += event.delta.y;
      }
    };
  };

}).call(this);
